name = "GroupedTemporalTerms"
uuid = "e3df3e69-96de-4eec-b47e-79221dc7d16c"
authors = ["Fabian Greimel <fabgrei@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
