name = "GroupedTemporalTerms"
uuid = "e3df3e69-96de-4eec-b47e-79221dc7d16c"
authors = ["Fabian Greimel <fabgrei@gmail.com> and contributors"]
version = "0.1.2"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
ShiftedArrays = "1277b4bf-5013-50f5-be3d-901d8477a67a"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
Underscores = "d9a01c3f-67ce-4d8c-9b55-35f6e4050bb1"

[compat]
DataFrames = "0.21, 0.22"
ShiftedArrays = "1"
StatsModels = "0.6"
Underscores = "2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
